apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: volume-nfs
entity:
  type: volume
  name: volume-nfs
  driver_type: humanitec/volume-nfs
  driver_inputs:
    values:
      path: "/"
      server: nfs-server.default.svc.cluster.local
  criteria:
  - class: nfs