# This Resource Definition uses the Template Driver 
# to add inject environment variables to a Workload
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: inject-env-var-to-workload
entity:
  name: inject-env-var-to-workload
  type: workload
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        outputs: |
          update:
            {{- range $containerId, $value := .resource.spec.containers }}
            - op: add
              path: /spec/containers/{{ $containerId }}/env
              value:
                - name: MY_ENV_VAR_A
                  value: "my env value A"
                - name: MY_ENV_VAR_B
                  value: "my env value B"
                - name: MY_ENV_VAR_C
                  value: "my env value C"
            {{- end }}