apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: s3-example-admin
entity:
  criteria:
    - app_id: example-delegator
      class: example-admin
  driver_inputs:
    values:
      # This Resource reference to 's3.example' creates the dependency to the base resource
      bucket: ${resources['s3.example'].outputs.bucket}
  provision:
    aws-policy.s3-example-admin:
      is_dependent: false
      match_dependents: true
  driver_type: humanitec/echo
  name: s3-example-admin
  type: s3
