# This Resource Definition specifies an `s3` Resource to be provisioned through OpenTofu code read from a private Git repository accessed via a password or token.
# The backend is defined via an inline file
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: s3-opentofu-container-runner
entity:
  name: S3 Bucket
  type: s3
  driver_type: humanitec/opentofu-container-runner
  # The Cloud Account referenced here provides the variables used in the credentials_config property
  # Use an account reference to get the Cloud Account name from a centralized config resource
  driver_account: ${resources['config.default#tf-config'].account}
  driver_inputs:
    values:
      runner:
        # Specify imagePullSecrets for pulling the runner image on the target cluster
        pod_template: |
          spec:
            imagePullSecrets:
              - name: ghcr-private-registry
      # Pull OpenTofu code from this Git repository
      source:
        ref: refs/tags/v1.2.3
        url: https://my-domain.com/my-org/my-repo.git
        username: my-git-handler
        path: path/to/s3
      # Define variables for the OpenTofu code
      variables:
        bucket: ${context.app.id}-${context.env.id}
      credentials_config:
        # These variables are provided by the Cloud Account referenced in the driver_account property
        # Setting the environment variables will configure the TF provider authentication
        environment:
          AWS_ACCESS_KEY_ID: AccessKeyId
          AWS_SECRET_ACCESS_KEY: SecretAccessKey
          AWS_SESSION_TOKEN: SessionToken
      use_default_backend: false
      files:
        # Define the TF backend dynamically
        backend.tf: |
          terraform {
            backend "s3" {
              # Read backend configuration values from the "tf-config" resource
              bucket = "${resources['config.default#tf-config'].outputs.backend_s3_bucket_name}"
              region = "${resources['config.default#tf-config'].outputs.backend_s3_bucket_region}"
              # Use placeholders to construct a unique path and key for the state file
              key    = "${context.org.id}/${context.app.id}/${context.env.id}/${context.res.guresid}.tfstate"
            }
          }
        # Define a provider block. Read configuration values from the tf-config resource
        provider-config.tf: |
          provider "aws" {
            region = "${resources['config.default#tf-config'].outputs.provider_aws_region}"
          }
    secret_refs:
      # Obtain the password for authenticating to the Git repository from a secret store
      source:
        password:
          store: my-store
          ref: path/to/git/password
  criteria:
    - env_type: development
