# This Resource Definition specifies a `tf-config` Resource for the Terraform/OpenTofu setup
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: config_tf_development
entity:
  driver_type: humanitec/echo
  name: tf-config-development
  type: config
  # Define the Cloud Account to be used by other Resources for provider authentication
  driver_account: my-cloud-account-id
  driver_inputs:
    # Define provider and backend parameters
    values:
      provider_aws_region: us-east-1
      backend_s3_bucket_name: my-s3-backend-bucket
      backend_s3_bucket_region: us-east-1
  criteria:
    # Change the env_type to match the name of the environment type you want this config to apply to
    - env_type: development
      res_id: tf-config  # Match this exact res_id
      class: default     # Match this exact class