# This "config" type Resource Definition provides the value for the sample label
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: app-config
entity:
  name: app-config
  type: config
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        # Returns a sample output named "substream_id" to be used as a label
        outputs: |
          substream_id: my-example-id
  # Set matching criteria as required
  criteria:
    - {}