# This Resource Definition uses the Echo Driver to represent a mysql-instance
# without managing it.
# In particular, it returns secret outputs for username and password, to be
# consumed by other upstream resources in the Graph.
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: container-driver-secrets-example-mysql-instance
entity:
  name: container-driver-secrets-example-mysql-instance
  type: mysql-instance
  driver_type: humanitec/echo
  driver_inputs:
    values:
      name: my-instance
      host: products.mysql.dev.example.com
      port: 5432
    secret_refs:
      # Read secret values from a secret store
      # which needs to be configured on the target cluster
      username:
        store: my-secret-store
        ref: my-instance-username
      password:
        store: my-secret-store
        ref: my-instance-password
  # Adjust matching criteria as required
  criteria:
  - app_id: container-driver-secrets-example