# This Resource Definition shows how to add annotations to the Kubernetes service object using the Template Driver
apiVersion: entity.humanitec.io/v1b1

kind: Definition
metadata:
  id: annotations
entity:
  name: annotations
  type: workload
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        outputs: |
          update:
            - op: add
              path: /spec/deployment/annotations
              value:
                {{- range $key, $val := .resource.spec.deployment.annotations }}
                {{ $key }}: {{ $val | quote }}
                {{- end }}
            - op: add
              path: /spec/pod/annotations
              value:
                {{- range $key, $val := .resource.spec.pod.annotations }}
                {{ $key }}: {{ $val | quote }}
                {{- end }}
            # If the Score file also defines a service, add annotations to the service object
            {{- if .resource.spec.service }}
            - op: add
              path: /spec/service/annotations
              value:
                {{- range $key, $val := .resource.spec.service.annotations }}
                {{ $key }}: {{ $val | quote }}
                {{- end }}
                {{- $port := values .resource.spec.service.ports | first }}
            - op: add
              path: /spec/service/annotations/cloud.google.com~1neg
              value: '{"ingress":true,"exposed_ports":{ {{- $port.service_port | quote -}} :{}}}'
            {{- end }}
  criteria:
    - {}
