
# Make sure all ${ENVIRONMENT_VARIABLES} are set when applying this Resource Definition.
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: gke-static-credentials
entity:
  name: gke-static-credentials
  type: k8s-cluster
  driver_type: humanitec/k8s-cluster-gke
  driver_inputs: 
    values: 
      loadbalancer: 35.10.10.10
      name: demo-123
      zone: europe-west2-a
      project_id: my-gcp-project
    secrets: 
      # The "credentials" data correspond to the content of the credentials.json
      # that Google Cloud generates for a service account key
      credentials:
        type: service_account
        project_id: my-gcp-project
        # Example private_key_id: 48b483fbf1d6e80fb4ac1a4626eb5d8036e3520f
        private_key_id: ${PRIVATE_KEY_ID}
        # Example private_key: -----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEbcASCBKgwggSkAgEBEoIBAQDP3mJrZeIFU9ni\\n4J7TZsvjkjtlExq1Sl7gYFp/ZeZPWPkRtCp1iKPpckRiZhbqxXkCjpLVHk4qpXYZ\\n7RYq5uXjd/PuHe2r6uuDAVmCvJtWorfKeL37feFsNkVAOAei7A5LHEtoA4ucIlvD\\fq+jX6qxcHYYTZaYh6qiktbpVo5s8kLN0fpJUVvOzLJtxz5ts3KDsPnZmmezYApaf\\nQL7d5u0liTDtYQV074XfOOha4olXrwLwDbk+oVZ3pVtB7LXDtZxO2J7NnA8EzueT\\n6wocySbGtoLPsVALsjZw9f0d7/UGQsqRYecXuWMBfX9+wOegWEDKemtZXFM3CE+N\\nXRLsecP/AgMBAAECggEAAPem+5r4x0+RlwW2l4NF9aQ/FuRU3n0fHVG1ehxOSxY9\\n6oAtJmjhYme+u7p/5s3Od12Uf1tpv7cPHS2gScjTTxCy2OvYvFEWkYCDGyGnk2qk\\nclPHhpEaaHeEMP1Rw8dXdbAHBc/maW6bgLjAc6jK7o7Qnex+LnA6IrIZ0OY3Bbwg\\ngpelVgQmlCMbjc7sNVhi/0Tjgo/2mzdnF5I5BXBaX5HAV71Vr773kVnq9z/f0zHC\\nMZ8G4Mrwhk2yW3e8+qm+iNCDkHD2hdF9S4Q8FexfHcFDUKE70UMt6pyhX3mVIlNw\\nfeW1+VnaQvrXwcQRgFtmoCaVUZzX+frPW2tns92kOQKBgQD30TycLi/Wx+QMpBeg\\n1dGy21ZJyrZfGslWCJG8ETxI0A38DWSJziHVCNAMJwHPmaNnHBMaSTvOdLz3neL9\\nBIuySvrGsUlF+0L31rv80GSQpUU78pVI5EtgkNear4alNYHPFgOm8XjeYn49429R\\n1GOdkuCZ0BcFEAZh/03VYVOtuwKBgQDWu3e9W3ZZ8xnQV893bWpT6mSVJfvAyc5l\\niqsoA7/IfapIm25GtIYVSqu92IYDjAjDzD1ZccXKHZS9UAX9PHVKEhhHx/JKetkP\\noQp0Z7UhWwn6kslllVvGGmnwMS01CIIvPRYsyui2SHT8RQNNQYu77z3vlpBaDSrF\\n6b9mca38jQKBgQCU2DzCRc9//pGPsiNq++I2vhzmt3WwS8NwBDecMPH3fddYc6bW\\nSlPxw5hKJEenLE2Dyc4DdMcSKvWw+Ej01X0eeoCDRMqQ2OiROY2xvG0an9mktwBJ\\nRq2rc3O8Of7yTeAIxN0usUx6rcfLXkZnbNzkMOrsF5sr9EMRKynRpuJ+rwKBgQCD\\njTogQeZR2QMZhpJNojSf0FtqnGiNhZTy1G9jBlj6JTKrZL28h2AVrzdkCUCg76t2\\n+KslHvSDjHfROzNQHzfj9w30++POCVDtqEVVZyuqkbGdV0wW9dfRl+ELC7WcZegL\\ntKrfKjhDZER3QHhzXhKTQlB5dY5d/O8VbMyboE1tCQKBgEToP+ijJAGtEJECahTb\\nAiZZouHbg738fhx0PC1wwRFTGNLlCoEjiFxMQxXaJ6HKsGzDok+T9Bvh/1hm0tRt\\niyWJNaDIwHAEj2iuk4fTH4UFQpGWzf+P6Mw9YPIyQrgMqZ6KNASSxRz1OqtGCzKH\\ngGBzPPgLNLjNcCPto1SRQ9nG\\n-----END PRIVATE KEY-----\\n
        private_key: ${PRIVATE_KEY}
        # Example client_id: 206964217359046819490
        client_id: ${CLIENT_ID}
        client_email: my-service-account@my-gcp-project.iam.gserviceaccount.com
        auth_uri: https://accounts.google.com/o/oauth2/auth
        token_uri: https://oauth2.googleapis.com/token
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/my-service-account%40my-gcp-project.iam.gserviceaccount.com
