# This Resource Defintion provisions a Kubernetes ServiceAccount
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: hpa
entity:
  driver_type: humanitec/template
  name: hpa
  type: horizontal-pod-autoscaler
  driver_inputs:
    values:
      templates:
        init: |
          workload: {{ index (splitList "." "${context.res.id}") 1 }}
          maxReplicas: {{ if .resource.maxReplicas }}{{ min .resource.maxReplicas 10 }}{{ else }}10{{ end }}
          minReplicas: {{ if .resource.minReplicas }}{{ max .resource.minReplicas 2 }}{{ else }}2{{ end }}
          targetCPUUtilizationPercentage: {{ if .resource.targetCPUUtilizationPercentage }}{{ max .resource.targetCPUUtilizationPercentage 80 }}{{ else }}80{{ end }}
        manifests: |
          hpa.yaml:
            location: namespace
            data:
              apiVersion: autoscaling/v2
              kind: HorizontalPodAutoscaler
              metadata:
                name: {{ .init.workload }}-hpa
              spec:
                maxReplicas: {{ .init.maxReplicas }}
                metrics:
                - resource:
                    name: cpu
                    target:
                      averageUtilization: {{ .init.targetCPUUtilizationPercentage }}
                      type: Utilization
                  type: Resource
                minReplicas: {{ .init.minReplicas }}
                scaleTargetRef:
                  apiVersion: apps/v1
                  kind: Deployment
                  name: {{ .init.workload }}
