# This Resource Definition uses the base-env Resource type to create
# a SecretStore definition in the namespace of the Application Environment
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: base-env
entity:
  name: base-env
  type: base-env
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        manifests: |-
          secretstore.yaml:
            location: namespace
            data:
              apiVersion: humanitec.io/v1alpha1
              kind: SecretStore
              metadata:
                name: my-local-gsm
              spec:
                # Configure the secret store according to its type
                # This example shows a Google Cloud Secret Manager
                gcpsm:
                  auth: {}
                  projectID: ${resources['config.secretstore'].outputs.project_id}
  # Adjust matching criteria as required
  criteria:
  - app_id: my-secretstore-app