# This Resource Definition uses the Echo Driver to provide configuration values
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: secretstore-config
entity:
  name: secretstore-config
  type: config
  driver_type: humanitec/echo
  driver_inputs:
    # Any Driver inputs will be returned as outputs by the Echo Driver
    values:
      project_id: my-gcp-project-id
  # Adjust matching criteria as required
  criteria:
  - class: secretstore
    app_id: my-secretstore-app