# This Resource Definition adds a Prometheus ServiceMonitor to a Workload
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: servicemonitor-workload
entity:
  driver_type: humanitec/template
  name: servicemonitor-workload
  type: workload
  driver_inputs:
    values:
      namespace: ${resources['k8s-namespace.default#k8s-namespace'].outputs.namespace}
      templates:
        init: |
          workload: {{ index (splitList "." "${context.res.id}") 1 }}
          {{- if .resource.spec.service }}
          servicePort: {{ get (.resource.spec.service.ports | values | first ) "service_port" }}
          {{- else }}
          servicePort: 8080
          {{- end }}
        manifests: |
          {{- if .resource.spec.service }}
          service-monitor.yaml:
            location: namespace
            data:
              apiVersion: monitoring.coreos.com/v1
              kind: ServiceMonitor
              metadata:
                name: {{ .init.workload }}-svc-monitor
              spec:
                endpoints:
                - interval: 30s
                  targetPort: {{ .init.servicePort }}
                  path: /metrics
                namespaceSelector:
                  matchNames:
                  - {{ .driver.values.namespace }}
                selector:
                  matchLabels:
                    humanitec.io/workload: {{ .init.workload }}
          {{- end }}
