apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: efs-volume
entity:
  name: efs-volume
  type: volume
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        init: |
          volumeUid: {{ randNumeric 4 }}-{{ randNumeric 4 }}
          pvBaseName: pv-tmpl-
          pvcBaseName: pvc-tmpl-
          volBaseName: vol-tmpl-
          capacity: 6Gi
          accessMode: ReadWriteMany
        manifests:
          pv.yaml:
            location: cluster
            data: |
              apiVersion: v1
              kind: PersistentVolume
              metadata:
                name: {{ .init.pvBaseName }}{{ .init.volumeUid }}
              spec:
                capacity:
                  storage: {{ .init.capacity }}
                volumeMode: Filesystem
                accessModes:
                  - {{ .init.accessMode }}
                storageClassName: efs-sc
                persistentVolumeReclaimPolicy: Retain
                csi:
                  driver: efs.csi.aws.com
                  volumeHandle: ${resources['config.default#efs'].outputs.efs_volume_handle}
                  volumeAttributes:
                    encryptInTransit: "true"
                    crossaccount: "true"
          pvc.yaml:
            location: namespace
            data: |
              apiVersion: v1
              kind: PersistentVolumeClaim
              metadata:
                name: {{ .init.pvcBaseName }}{{ .init.volumeUid }}
              spec:
                accessModes:
                  - {{ .init.accessMode }}
                storageClassName: efs-sc
                resources:
                  requests:
                    storage: {{ .init.capacity }}
                volumeName: {{ .init.pvBaseName }}{{ .init.volumeUid }}
          volume.yaml:
            location: volumes
            data: |
              name: {{ .init.volBaseName }}{{ .init.volumeUid }}
              persistentVolumeClaim:
                claimName: {{ .init.pvcBaseName }}{{ .init.volumeUid }}
  criteria:
    - class: efs