name: ci
permissions:
  contents: read
  id-token: write
on:
  pull_request:
jobs:
  score-validate:
    runs-on: ubuntu-24.04
    env:
      HUMCTL_VERSION: '*'
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install humctl
        uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: humctl score validate
        run: |
          scoreFiles=$(ls -d score/*/score.yaml)
          for scoreFile in ${scoreFiles}
          do
            humctl score validate ${scoreFile} \
              --strict \
              --local
          done
          